In [ ]:
import pandas as pd
import numpy as np

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('menu2.csv')

In [ ]:
df.head()

,Category,Item,Serving_Size,Calories,Calories_from_Fat,Total_Fat,Total_Fat(%DailyValue),Saturated_Fat,Saturated_Fat(%DailyValue),Trans_Fat,...,Carbohydrates,Carbohydrates(%DailyValue),Dietary_Fiber,Dietary_Fiber(%DailyValue),Sugars,Protein,Vitamin_A(%DailyValue),Vitamin_C(%DailyValue),Calcium(%DailyValue),Iron(%DailyValue)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120.0,13.0,20.0,5.0,25.0,0.0,...,31.0,10.0,4.0,17.0,3.0,17.0,10.0,0.0,25.0,15.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250.0,70.0,8.0,12.0,3.0,15.0,0.0,...,30.0,10.0,4.0,17.0,3.0,18.0,6.0,0.0,25.0,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370.0,200.0,23.0,35.0,8.0,42.0,0.0,...,29.0,10.0,4.0,17.0,2.0,14.0,8.0,0.0,25.0,10.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250.0,28.0,43.0,10.0,52.0,0.0,...,30.0,10.0,4.0,17.0,2.0,21.0,15.0,0.0,30.0,15.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210.0,23.0,35.0,8.0,42.0,0.0,...,30.0,10.0,4.0,17.0,2.0,21.0,6.0,0.0,25.0,10.0

In [ ]:
data = df.drop(['Item','Serving_Size'],axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Category                    260 non-null    object
 1   Calories                    249 non-null    float64
 2   Calories_from_Fat           249 non-null    float64
 3   Total_Fat                   249 non-null    float64
 4   Total_Fat(%DailyValue)      249 non-null    float64
 5   Saturated_Fat               249 non-null    float64
 6   Saturated_Fat(%DailyValue)  249 non-null    float64
 7   Trans_Fat                   249 non-null    float64
 8   Cholesterol                 249 non-null    float64
 9   Cholesterol(%DailyValue)    249 non-null    float64
 10  Sodium                      249 non-null    float64
 11  Sodium(%DailyValue)         249 non-null    float64
 12  Carbohydrates               249 non-null    float64
 13  Carbohydrates(%DailyValue)  249 non-null    float64
 14  Dietary_Fiber               249 non-null    float64
 15  Dietary_Fiber(%DailyValue)  249 non-null    float64
 16  Sugars                      249 non-null    float64
 17  Protein                     249 non-null    float64
 18  Vitamin_A(%DailyValue)      249 non-null    float64
 19  Vitamin_C(%DailyValue)      249 non-null    float64
 20  Calcium(%DailyValue)        249 non-null    float64
 21  Iron(%DailyValue)           249 non-null    float64
dtypes: float64(21), object(1)
memory usage: 44.8+ KB

In [ ]:
data.head()

,Category,Calories,Calories_from_Fat,Total_Fat,Total_Fat(%DailyValue),Saturated_Fat,Saturated_Fat(%DailyValue),Trans_Fat,Cholesterol,Cholesterol(%DailyValue),...,Carbohydrates,Carbohydrates(%DailyValue),Dietary_Fiber,Dietary_Fiber(%DailyValue),Sugars,Protein,Vitamin_A(%DailyValue),Vitamin_C(%DailyValue),Calcium(%DailyValue),Iron(%DailyValue)
0,Breakfast,300.0,120.0,13.0,20.0,5.0,25.0,0.0,260.0,87.0,...,31.0,10.0,4.0,17.0,3.0,17.0,10.0,0.0,25.0,15.0
1,Breakfast,250.0,70.0,8.0,12.0,3.0,15.0,0.0,25.0,8.0,...,30.0,10.0,4.0,17.0,3.0,18.0,6.0,0.0,25.0,8.0
2,Breakfast,370.0,200.0,23.0,35.0,8.0,42.0,0.0,45.0,15.0,...,29.0,10.0,4.0,17.0,2.0,14.0,8.0,0.0,25.0,10.0
3,Breakfast,450.0,250.0,28.0,43.0,10.0,52.0,0.0,285.0,95.0,...,30.0,10.0,4.0,17.0,2.0,21.0,15.0,0.0,30.0,15.0
4,Breakfast,400.0,210.0,23.0,35.0,8.0,42.0,0.0,50.0,16.0,...,30.0,10.0,4.0,17.0,2.0,21.0,6.0,0.0,25.0,10.0

In [ ]:
data.isnull().sum().sort_values(ascending=False)

Sodium(%DailyValue)           11
Calories                      11
Calcium(%DailyValue)          11
Vitamin_C(%DailyValue)        11
Vitamin_A(%DailyValue)        11
Protein                       11
Sugars                        11
Dietary_Fiber(%DailyValue)    11
Dietary_Fiber                 11
Carbohydrates(%DailyValue)    11
Carbohydrates                 11
Iron(%DailyValue)             11
Sodium                        11
Cholesterol(%DailyValue)      11
Cholesterol                   11
Trans_Fat                     11
Saturated_Fat(%DailyValue)    11
Saturated_Fat                 11
Total_Fat(%DailyValue)        11
Total_Fat                     11
Calories_from_Fat             11
Category                       0
dtype: int64

In [ ]:
data['Category'].value_counts()

1.0    95
2.0    31
3.0    28
5.0    27
4.0    27
6.0    15
7.0    13
8.0     7
9.0     6
Name: Category, dtype: int64

In [ ]:
data['Sodium(%DailyValue)'] = data['Sodium(%DailyValue)'].fillna(data['Sodium(%DailyValue)'].mean())
data['Calories'] = data['Calories'].fillna(data['Calories'].mean())
data['Calcium(%DailyValue)'] = data['Calcium(%DailyValue)'].fillna(data['Calcium(%DailyValue)'].mean())
data['Vitamin_C(%DailyValue)'] = data['Vitamin_C(%DailyValue)'].fillna(data['Vitamin_C(%DailyValue)'].mean())
data['Vitamin_A(%DailyValue)'] = data['Vitamin_A(%DailyValue)'].fillna(data['Vitamin_A(%DailyValue)'].mean())
data['Protein'] = data['Protein'].fillna(data['Protein'].mean())
data['Sugars'] = data['Sugars'].fillna(data['Sugars'].mean())
data['Dietary_Fiber(%DailyValue)'] = data['Dietary_Fiber(%DailyValue)'].fillna(data['Dietary_Fiber(%DailyValue)'].mean())
data['Dietary_Fiber'] = data['Dietary_Fiber'].fillna(data['Dietary_Fiber'].mean())
data['Carbohydrates(%DailyValue)'] = data['Carbohydrates(%DailyValue)'].fillna(data['Carbohydrates(%DailyValue)'].mean())
data['Dietary_Fiber'] = data['Dietary_Fiber'].fillna(data['Dietary_Fiber'].mean())
data['Carbohydrates(%DailyValue)'] = data['Carbohydrates(%DailyValue)'].fillna(data['Carbohydrates(%DailyValue)'].mean())
data['Carbohydrates'] = data['Carbohydrates'].fillna(data['Carbohydrates'].mean())
data['Iron(%DailyValue)'] = data['Iron(%DailyValue)'].fillna(data['Iron(%DailyValue)'].mean())
data['Sodium'] = data['Sodium'].fillna(data['Sodium'].mean())
data['Cholesterol(%DailyValue)'] = data['Cholesterol(%DailyValue)'].fillna(data['Cholesterol(%DailyValue)'].mean())
data['Cholesterol'] = data['Cholesterol'].fillna(data['Cholesterol'].mean())
data['Trans_Fat'] = data['Trans_Fat'].fillna(data['Trans_Fat'].mean())
data['Saturated_Fat(%DailyValue)'] = data['Saturated_Fat(%DailyValue)'].fillna(data['Saturated_Fat(%DailyValue)'].mean())
data['Saturated_Fat'] = data['Saturated_Fat'].fillna(data['Saturated_Fat'].mean())
data['Total_Fat(%DailyValue)'] = data['Total_Fat(%DailyValue)'].fillna(data['Total_Fat(%DailyValue)'].mean())
data['Total_Fat'] = data['Total_Fat'].fillna(data['Total_Fat'].mean())
data['Calories_from_Fat'] = data['Calories_from_Fat'].fillna(data['Calories_from_Fat'].mean())

In [ ]:
data.isnull().sum().sort_values(ascending=False)

Category                      0
Calories                      0
Calcium(%DailyValue)          0
Vitamin_C(%DailyValue)        0
Vitamin_A(%DailyValue)        0
Protein                       0
Sugars                        0
Dietary_Fiber(%DailyValue)    0
Dietary_Fiber                 0
Carbohydrates(%DailyValue)    0
Carbohydrates                 0
Sodium(%DailyValue)           0
Sodium                        0
Cholesterol(%DailyValue)      0
Cholesterol                   0
Trans_Fat                     0
Saturated_Fat(%DailyValue)    0
Saturated_Fat                 0
Total_Fat(%DailyValue)        0
Total_Fat                     0
Calories_from_Fat             0
Iron(%DailyValue)             0
dtype: int64

In [ ]:
data['Category'].value_counts()

Coffee & Tea                                                                                                                                             95
Breakfast                                                                                                                                                31
Smoothies & Shakes                                                                                                                                       28
Beverages                                                                                                                                                27
Chicken & Fish                                                                                                                                           27
Beef & Pork                                                                                                                                              15
Snacks & Sides                                                                                                                                           13
Desserts                                                                                                                                                  7
Salads                                                                                                                                                    6
Breakfast,"Bacon, Egg & Cheese Biscuit with Egg Whites (Regular Biscuit)",5.4 oz (153 g),410,180,20,32,11,56,0,35,11,1300,54,36,12,2,7,3,20,2,8,15,10     1
Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520,270,30,47,14,68,0,250,83,1410,59,43,14,3,12,4,19,15,8,20,20                    1
Breakfast,"Steak, Egg & Cheese Bagel",8.5 oz (241 g),670,310,35,53,13,63,1.5,295,99,1510,63,56,19,3,12,7,33,20,4,25,25                                    1
Breakfast,"Bacon, Egg & Cheese Biscuit with Egg Whites (Large Biscuit)",5.9 oz (167 g),470,220,25,38,12,59,0,35,11,1420,59,42,14,3,12,4,20,6,8,15,15      1
Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460,230,26,40,13,65,0,250,83,1300,54,38,13,2,7,3,19,10,8,15,15                   1
Breakfast,"Bacon, Egg & Cheese Bagel",6.9 oz (197 g),620,280,31,48,11,56,0.5,275,92,1480,62,57,19,3,11,7,30,20,15,20,20                                   1
Breakfast,"Sausage, Egg & Cheese McGriddles with Egg Whites",7.2 oz (205 g),500,230,26,40,10,52,0,50,17,1320,55,46,15,2,9,15,21,2,0,20,10                 1
Breakfast,"Sausage, Egg & Cheese McGriddles",7.1 oz (201 g),550,280,31,48,12,61,0,265,89,1320,55,48,16,2,9,15,20,10,0,20,15                               1
Breakfast,"Bacon, Egg & Cheese McGriddles with Egg Whites",6.3 oz (178 g),400,140,15,24,7,34,0,35,11,1250,52,47,16,2,9,16,20,2,10,15,10                   1
Breakfast,"Bacon, Egg & Cheese McGriddles",6.1 oz (174 g),460,190,21,32,9,44,0,250,84,1250,52,48,16,2,9,15,19,10,10,20,15                                 1
Breakfast,"Bacon, Egg & Cheese Bagel with Egg Whites",7.1 oz (201 g),570,230,25,39,9,45,0.5,60,20,1480,62,55,18,3,12,8,30,10,15,20,15                     1
Name: Category, dtype: int64

In [ ]:
data['Category'] = data['Category'].map({'Coffee & Tea':1, 'Breakfast':2, 'Smoothies & Shakes':3, 'Beverages':4, 'Chicken & Fish':5, 'Beef & Pork':6, 'Snacks & Sides':7, 'Desserts':8, 'Salads':9})

In [ ]:
data.head()

,Category,Calories,Calories_from_Fat,Total_Fat,Total_Fat(%DailyValue),Saturated_Fat,Saturated_Fat(%DailyValue),Trans_Fat,Cholesterol,Cholesterol(%DailyValue),...,Carbohydrates,Carbohydrates(%DailyValue),Dietary_Fiber,Dietary_Fiber(%DailyValue),Sugars,Protein,Vitamin_A(%DailyValue),Vitamin_C(%DailyValue),Calcium(%DailyValue),Iron(%DailyValue)
0,2.0,300.0,120.0,13.0,20.0,5.0,25.0,0.0,260.0,87.0,...,31.0,10.0,4.0,17.0,3.0,17.0,10.0,0.0,25.0,15.0
1,2.0,250.0,70.0,8.0,12.0,3.0,15.0,0.0,25.0,8.0,...,30.0,10.0,4.0,17.0,3.0,18.0,6.0,0.0,25.0,8.0
2,2.0,370.0,200.0,23.0,35.0,8.0,42.0,0.0,45.0,15.0,...,29.0,10.0,4.0,17.0,2.0,14.0,8.0,0.0,25.0,10.0
3,2.0,450.0,250.0,28.0,43.0,10.0,52.0,0.0,285.0,95.0,...,30.0,10.0,4.0,17.0,2.0,21.0,15.0,0.0,30.0,15.0
4,2.0,400.0,210.0,23.0,35.0,8.0,42.0,0.0,50.0,16.0,...,30.0,10.0,4.0,17.0,2.0,21.0,6.0,0.0,25.0,10.0

In [ ]:
data['Category'].value_counts()
# data.head()

1.0    95
2.0    31
3.0    28
5.0    27
4.0    27
6.0    15
7.0    13
8.0     7
9.0     6
Name: Category, dtype: int64

In [ ]:
data.isnull().sum().sort_values(ascending=False)

Category                      0
Calories                      0
Calcium(%DailyValue)          0
Vitamin_C(%DailyValue)        0
Vitamin_A(%DailyValue)        0
Protein                       0
Sugars                        0
Dietary_Fiber(%DailyValue)    0
Dietary_Fiber                 0
Carbohydrates(%DailyValue)    0
Carbohydrates                 0
Sodium(%DailyValue)           0
Sodium                        0
Cholesterol(%DailyValue)      0
Cholesterol                   0
Trans_Fat                     0
Saturated_Fat(%DailyValue)    0
Saturated_Fat                 0
Total_Fat(%DailyValue)        0
Total_Fat                     0
Calories_from_Fat             0
Iron(%DailyValue)             0
dtype: int64

In [ ]:
data.drop(index=[6, 7, 8, 9, 19, 20, 22, 23, 24, 25, 26], inplace=True)

In [ ]:
# data['Category'] = data['Category'].fillna(data['Category'].mode())

In [ ]:
# data.dropna(axis=0, how='any', inplace=False)

,Category,Calories,Calories_from_Fat,Total_Fat,Total_Fat(%DailyValue),Saturated_Fat,Saturated_Fat(%DailyValue),Trans_Fat,Cholesterol,Cholesterol(%DailyValue),...,Carbohydrates,Carbohydrates(%DailyValue),Dietary_Fiber,Dietary_Fiber(%DailyValue),Sugars,Protein,Vitamin_A(%DailyValue),Vitamin_C(%DailyValue),Calcium(%DailyValue),Iron(%DailyValue)
0,2.0,300.0,120.0,13.0,20.0,5.0,25.0,0.0,260.0,87.0,...,31.0,10.0,4.0,17.0,3.0,17.0,10.0,0.0,25.0,15.0
1,2.0,250.0,70.0,8.0,12.0,3.0,15.0,0.0,25.0,8.0,...,30.0,10.0,4.0,17.0,3.0,18.0,6.0,0.0,25.0,8.0
2,2.0,370.0,200.0,23.0,35.0,8.0,42.0,0.0,45.0,15.0,...,29.0,10.0,4.0,17.0,2.0,14.0,8.0,0.0,25.0,10.0
3,2.0,450.0,250.0,28.0,43.0,10.0,52.0,0.0,285.0,95.0,...,30.0,10.0,4.0,17.0,2.0,21.0,15.0,0.0,30.0,15.0
4,2.0,400.0,210.0,23.0,35.0,8.0,42.0,0.0,50.0,16.0,...,30.0,10.0,4.0,17.0,2.0,21.0,6.0,0.0,25.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,3.0,510.0,150.0,17.0,26.0,9.0,44.0,0.5,45.0,14.0,...,80.0,27.0,1.0,4.0,64.0,12.0,15.0,0.0,40.0,8.0
256,3.0,690.0,200.0,23.0,35.0,12.0,58.0,1.0,55.0,19.0,...,106.0,35.0,1.0,5.0,85.0,15.0,20.0,0.0,50.0,10.0
257,3.0,340.0,100.0,11.0,17.0,6.0,29.0,0.0,30.0,9.0,...,53.0,18.0,1.0,2.0,43.0,8.0,10.0,0.0,25.0,6.0
258,3.0,810.0,290.0,32.0,50.0,15.0,76.0,1.0,60.0,20.0,...,114.0,38.0,2.0,9.0,103.0,21.0,20.0,0.0,60.0,6.0
259,3.0,410.0,150.0,16.0,25.0,8.0,38.0,0.0,30.0,10.0,...,57.0,19.0,1.0,5.0,51.0,10.0,10.0,0.0,30.0,4.0

In [ ]:
# data.isna().sum()

Category                      11
Calories                       0
Calories_from_Fat              0
Total_Fat                      0
Total_Fat(%DailyValue)         0
Saturated_Fat                  0
Saturated_Fat(%DailyValue)     0
Trans_Fat                      0
Cholesterol                    0
Cholesterol(%DailyValue)       0
Sodium                         0
Sodium(%DailyValue)            0
Carbohydrates                  0
Carbohydrates(%DailyValue)     0
Dietary_Fiber                  0
Dietary_Fiber(%DailyValue)     0
Sugars                         0
Protein                        0
Vitamin_A(%DailyValue)         0
Vitamin_C(%DailyValue)         0
Calcium(%DailyValue)           0
Iron(%DailyValue)              0
dtype: int64

In [ ]:
X = data.drop (columns='Category', axis=1)
Y = data['Category']

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X)

StandardScaler()

In [ ]:
std = scaler.transform(X)

In [ ]:
X = std
Y = data['Category']

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, stratify=Y, random_state=2)

In [ ]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [ ]:
X_train_pred = model.predict(X_train)

In [ ]:
training_data_accuracy = accuracy_score(X_train_pred, Y_train)

In [ ]:
print('akurasi : ', training_data_accuracy)

akurasi :  0.8548387096774194

In [ ]:
X_test_pred = model.predict(X_test)

In [ ]:
test_data_accuracy = accuracy_score(X_test_pred, Y_test)

In [ ]:
print('akurasi : ', test_data_accuracy)

akurasi :  0.8253968253968254

In [ ]:
input_data = (300,120,13,20,5,25,0,260,87,750,31,31,10,4,17,3,17,10,0,25,15)
input_data_np = np.array(input_data)
input_data_reshape = input_data_np.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)

prediksi = model.predict(std_data)
print(prediksi)

if(prediksi[0] == 1 ):
  print("kopi dan teh")
elif(prediksi[0] == 2 ):
  print("breakfast")
elif(prediksi[0] == 3 ):
  print("smoothies")
elif(prediksi[0] == 4 ):
  print("beverages")
elif(prediksi[0] == 5 ):
  print("chicken and fish")
elif(prediksi[0] == 6 ):
  print("beef and pork")
elif(prediksi[0] == 7 ):
  print("snacks")
elif(prediksi[0] == 8 ):
  print("dessert")
elif(prediksi[0] == 9 ):
  print("salads")
else:
  print('salah')

[2.]
kopi dan teh

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
import pickle

filename = 'category_mcd.sav'
pickle.dump(model, open(filename, 'wb'))